# Generated by Django 3.0.1 on 2020-02-26 10:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('NE', 'NEW'), ('HA', 'HANDLING'), ('CA', 'CANCELED'), ('CO', 'COMPLITED')], default='NE', max_length=2)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField()),
                ('slug', models.SlugField(unique=True)),
                ('is_available', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_value', models.CharField(max_length=100)),
                ('delta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('is_default', models.BooleanField()),
                ('no_compatible_options', models.ManyToManyField(blank=True, related_name='_productoptions_no_compatible_options_+', to='shop.ProductOptions')),
                ('option_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='shop.OptionGroup')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('total_price', models.IntegerField(default=0)),
                ('options', models.ManyToManyField(to='shop.ProductOptions')),
                ('order', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.Order')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='main_option',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.ProductOptions'),
        ),
        migrations.AddField(
            model_name='optiongroup',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='shop.Product'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to='shop/static/media/products_images')),
                ('options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.ProductOptions')),
            ],
        ),
    ]
