# Generated by Django 3.0.1 on 2020-02-26 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200226_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_option',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.ProductOptions'),
        ),
    ]
