# Generated by Django 3.0.1 on 2020-01-01 18:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200101_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NE', 'NEW'), ('HA', 'HANDLING'), ('CA', 'CANCELED'), ('CO', 'COMPLITED')], default='NE', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
