# Generated by Django 3.0.3 on 2020-03-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200228_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='addition',
            field=models.TextField(default='', max_length=600),
        ),
    ]
