# Generated by Django 3.0.1 on 2020-01-03 08:47

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200101_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='media/products_images'), size=None),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='shop.Product'),
        ),
    ]
