# Generated by Django 3.0.3 on 2020-03-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200301_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='addition',
            field=models.TextField(blank=True, default='', max_length=600, null=True),
        ),
    ]
