# Generated by Django 3.0.1 on 2020-01-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200106_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
