# Generated by Django 3.0.1 on 2020-01-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200106_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='product',
        ),
        migrations.AddField(
            model_name='productinorder',
            name='product',
            field=models.ManyToManyField(related_name='order_items', to='shop.Product'),
        ),
    ]
