# Generated by Django 3.0.1 on 2020-01-05 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200106_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='product',
        ),
        migrations.AddField(
            model_name='productinorder',
            name='product',
            field=models.ForeignKey(default='empty', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.Product'),
            preserve_default=False,
        ),
    ]
