# Generated by Django 3.0.1 on 2020-01-06 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200106_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.Product'),
        ),
    ]
