# Generated by Django 3.0.2 on 2020-01-26 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200106_1458'),
        ('shop', '0013_auto_20200105_0131'),
    ]

    operations = [
    ]
